# fly.toml file generated for polyglot on 2023-03-18T03:39:46+07:00

app = "polyglot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = false
